spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "http://host.docker.internal:8080"
                allowedMethods: "*"
                allowedHeaders: "*"