spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "http://host.docker.internal:8080"
                allowedMethods: ["GET", "POST", "OPTIONS"]
                allowedHeaders: "*"

logging:
  level:
    com.example: TRACE
    org.springframework.web.cors: TRACE
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG